table_one:
  key: id
  conditions:
    - where user_id != 1
    - or cake LIKE %test%
  columns:
    firstname: firstname
    lastname: lastname

table_two:
  key: id
  columns:
    firstname: firstname
    lastname: lastname

table_three:
  key: id
  conditions: where user_id = 1
  columns:
    firstname: firstname
    lastname: lastname